sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t okkiman1/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true okkiman1/docker-react2 npm run test
